name: EtherosAuthBukkit
version: '1.0.0'
main: cn.skilfully.etheros.EtherosAuthBukkit
api-version: '1.17'
commands:
    etherosauth:
        aliases:
            - ea
    login:
        aliases:
            - l
    resetPassword:
        aliases: []
    register:
        aliases:
            - reg
depend:
    - EtherosCore
