CREATE TABLE IF NOT EXISTS player_account(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    uuid UUID NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS player_location (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    world VARCHAR(255) NOT NULL,
    x DOUBLE NOT NULL,
    y DOUBLE NOT NULL,
    z DOUBLE NOT NULL,
    yaw DOUBLE NOT NULL,
    pitch DOUBLE NOT NULL,

    INDEX idx_world (world)
)